<a href="https://colab.research.google.com/github/Jeevanandhini-18/AirQualityPrediction/blob/main/Air_Quality_Prediction_using_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

**Data preprocessing**

All the values in the csv file are separated by ' ; '
and few columns have ' , ' in place of ' . '

In [ ]:
# loading data from csv file to pandas dataframe
air_quality_data = pd.read_csv('/content/AirQuality.csv',sep=';',decimal=',')

# printing the first 5 rows of the dataframe
air_quality_data.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

In [ ]:
# removing the last two columns which has NaN values (usinf slicing)
air_quality_data = air_quality_data.iloc[:,:-2]

# printing the last 5 rows of the dataframe
air_quality_data.tail()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# checking the number of rows and columns
air_quality_data.shape

(9471, 15)

In [ ]:
# printing the last row
air_quality_data.loc[[9356]]

In [ ]:
# printing the first 9357 rows(the rows that doesn't have NaN values)
air_quality_data = air_quality_data.head(9357)
print(air_quality_data)

            Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10/03/2004  18.00.00     2.6       1360.0     150.0      11.9
1     10/03/2004  19.00.00     2.0       1292.0     112.0       9.4
2     10/03/2004  20.00.00     2.2       1402.0      88.0       9.0
3     10/03/2004  21.00.00     2.2       1376.0      80.0       9.2
4     10/03/2004  22.00.00     1.6       1272.0      51.0       6.5
...          ...       ...     ...          ...       ...       ...
9352  04/04/2005  10.00.00     3.1       1314.0    -200.0      13.5
9353  04/04/2005  11.00.00     2.4       1163.0    -200.0      11.4
9354  04/04/2005  12.00.00     2.4       1142.0    -200.0      12.4
9355  04/04/2005  13.00.00     2.1       1003.0    -200.0       9.5
9356  04/04/2005  14.00.00     2.2       1071.0    -200.0      11.9

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0
1             955.0    103.0        1174.0     92.0        1559.0
2             939.0    131.0        1140.0    114.0        1555.0
3             948.0    172.0        1092.0    122.0        1584.0
4             836.0    131.0        1205.0    116.0        1490.0
...             ...      ...           ...      ...           ...
9352         1101.0    472.0         539.0    190.0        1374.0
9353         1027.0    353.0         604.0    179.0        1264.0
9354         1063.0    293.0         603.0    175.0        1241.0
9355          961.0    235.0         702.0    156.0        1041.0
9356         1047.0    265.0         654.0    168.0        1129.0

      PT08.S5(O3)     T    RH      AH
0          1268.0  13.6  48.9  0.7578
1           972.0  13.3  47.7  0.7255
2          1074.0  11.9  54.0  0.7502
3          1203.0  11.0  60.0  0.7867
4          1110.0  11.2  59.6  0.7888
...           ...   ...   ...     ...
9352       1729.0  21.9  29.3  0.7568
9353       1269.0  24.3  23.7  0.7119
9354       1092.0  26.9  18.3  0.6406
9355        770.0  28.3  13.5  0.5139
9356        816.0  28.5  13.1  0.5028

[9357 rows x 15 columns]

In [ ]:
air_quality_data.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [ ]:
air_quality_data.tail()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
9352,04/04/2005,10.00.00,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11.00.00,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12.00.00,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13.00.00,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14.00.00,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [ ]:
air_quality_data.shape

(9357, 15)

In [ ]:
# checking the info of the data
air_quality_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: float64(13), object(2)
memory usage: 1.1+ MB

In [ ]:
# checking the number of missing values in the dataframe
air_quality_data.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

This shows there is no null values, But in this dataset, Missing values are tagged with -200 value. (Described in Kaggle)

In [ ]:
# counting the number of times -200 appears in the data
air_quality_data.isin([-200]).sum(axis=0)

Date                0
Time                0
CO(GT)           1683
PT08.S1(CO)       366
NMHC(GT)         8443
C6H6(GT)          366
PT08.S2(NMHC)     366
NOx(GT)          1639
PT08.S3(NOx)      366
NO2(GT)          1642
PT08.S4(NO2)      366
PT08.S5(O3)       366
T                 366
RH                366
AH                366
dtype: int64

**Handling the missing values**

In [ ]:
# convert all -200 values to NaN values and replace all NaN values with mean of the specific column
# converting -200 into NaN
air_quality_data = air_quality_data.replace(to_replace = -200,value = np.nan)
air_quality_data.tail()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
9352,04/04/2005,10.00.00,3.1,1314.0,NaN,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11.00.00,2.4,1163.0,NaN,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12.00.00,2.4,1142.0,NaN,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13.00.00,2.1,1003.0,NaN,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14.00.00,2.2,1071.0,NaN,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [ ]:
# finding the mean of each column
air_quality_data.select_dtypes(include='number').mean()

CO(GT)              2.152750
PT08.S1(CO)      1099.833166
NMHC(GT)          218.811816
C6H6(GT)           10.083105
PT08.S2(NMHC)     939.153376
NOx(GT)           246.896735
PT08.S3(NOx)      835.493605
NO2(GT)           113.091251
PT08.S4(NO2)     1456.264598
PT08.S5(O3)      1022.906128
T                  18.317829
RH                 49.234201
AH                  1.025530
dtype: float64

In [ ]:
# replacing the missing values with mean value
air_quality_data = air_quality_data.fillna(air_quality_data.select_dtypes(include='number').mean())
air_quality_data.tail()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
9352,04/04/2005,10.00.00,3.1,1314.0,218.811816,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11.00.00,2.4,1163.0,218.811816,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12.00.00,2.4,1142.0,218.811816,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13.00.00,2.1,1003.0,218.811816,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14.00.00,2.2,1071.0,218.811816,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [ ]:
# checking the number of missing values in the dataframe
air_quality_data.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [ ]:
# Check for duplicates
duplicate_count = air_quality_data.duplicated().sum()
print(f"Duplicate Rows: {duplicate_count}")

# Remove duplicates if any
air_quality_data.drop_duplicates(inplace=True)

Duplicate Rows: 0

In [ ]:
# Convert time from 'HH.MM.SS' to 'HH:MM:SS'
air_quality_data['Time'] = air_quality_data['Time'].str.replace('.', ':', regex=False)
air_quality_data.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [ ]:
# combine date and time column (useful for forecasting)
air_quality_data['DateTime'] = pd.to_datetime(air_quality_data['Date'] + ' ' + air_quality_data['Time'], dayfirst=True)
air_quality_data = air_quality_data.drop(columns=['Date', 'Time'])
air_quality_data.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,DateTime
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,2004-03-10 18:00:00
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,2004-03-10 19:00:00
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,2004-03-10 20:00:00
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,2004-03-10 21:00:00
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,2004-03-10 22:00:00

In [ ]:
# Importing matplotlib to help with visualizations
import matplotlib.pyplot as plt

# Selecting only the numeric columns to check for outliers
num_cols = air_quality_data.select_dtypes(include='number').columns

# Looping through each numeric column to identify and handle outliers
for column in num_cols:
    q1 = air_quality_data[column].quantile(0.25)
    q3 = air_quality_data[column].quantile(0.75)
    iqr = q3 - q1

    # Setting thresholds to detect outliers
    lower_limit = q1 - 1.5 * iqr
    upper_limit = q3 + 1.5 * iqr

    # Finding outliers that fall outside the defined range
    outlier_rows = air_quality_data[(air_quality_data[column] < lower_limit) | (air_quality_data[column] > upper_limit)]
    print(f"{column} - Total outliers: {len(outlier_rows)}")

    # Replacing outliers with the median value of the column
    col_median = air_quality_data[column].median()
    air_quality_data[column] = air_quality_data[column].apply(lambda x: col_median if x < lower_limit or x > upper_limit else x)

CO(GT) - Total outliers: 454
PT08.S1(CO) - Total outliers: 145
NMHC(GT) - Total outliers: 914
C6H6(GT) - Total outliers: 286
PT08.S2(NMHC) - Total outliers: 91
NOx(GT) - Total outliers: 778
PT08.S3(NOx) - Total outliers: 278
NO2(GT) - Total outliers: 380
PT08.S4(NO2) - Total outliers: 131
PT08.S5(O3) - Total outliers: 131
T - Total outliers: 10
RH - Total outliers: 0
AH - Total outliers: 7

In [ ]:
from sklearn.preprocessing import StandardScaler

# Select only numeric columns for scaling
numeric_cols = air_quality_data.select_dtypes(include='number').columns

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the data
air_quality_data[numeric_cols] = scaler.fit_transform(air_quality_data[numeric_cols])

# Show the result
air_quality_data.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,DateTime
0,0.652882,1.380540,-5.684342e-14,0.429411,0.463280,-0.340164,1.177073,0.116752,0.780450,0.717079,-0.544297,-0.019689,-0.676336,2004-03-10 18:00:00
1,0.032349,1.033714,-5.684342e-14,0.010895,0.096733,-0.900077,1.745470,-0.459921,0.362313,-0.093547,-0.579104,-0.090386,-0.758194,2004-03-10 19:00:00
2,0.239193,1.594756,-5.684342e-14,-0.056067,0.032285,-0.651227,1.581695,0.144213,0.349738,0.185790,-0.741538,0.280772,-0.695597,2004-03-10 20:00:00
3,0.239193,1.462146,-5.684342e-14,-0.022586,0.068537,-0.286839,1.350482,0.363898,0.440911,0.539070,-0.845959,0.634256,-0.603094,2004-03-10 21:00:00
4,-0.381340,0.931706,-5.684342e-14,-0.474583,-0.382598,-0.651227,1.894795,0.199134,0.145386,0.284380,-0.822754,0.610691,-0.597771,2004-03-10 22:00:00

In [14]:
# Set Git user info (use your GitHub username and email)
!git config --global user.name "Shwetha-29"
!git config --global user.email "shwethamuthuselvan29@gmail.com"

In [1]:
# Replace with your repository link
!git clone https://github.com/Jeevanandhini-18/AirQualityPrediction.git

Cloning into 'AirQualityPrediction'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), 243.12 KiB | 1.58 MiB/s, done.

In [ ]:
!ls

AirQuality.csv	AirQualityPrediction  Air_Quality_Prediction_using_ML.ipynb

In [2]:
%cd AirQualityPrediction

/content/AirQualityPrediction

In [3]:
!find /content -name "Air_Quality_Prediction_using_ML.ipynb"

/content/Air_Quality_Prediction_using_ML.ipynb

In [4]:
import shutil
shutil.copy("/content/Air_Quality_Prediction_using_ML.ipynb", "/content/AirQualityPrediction/")

'/content/AirQualityPrediction/Air_Quality_Prediction_using_ML.ipynb'

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
!cp /content/Air_Quality_Prediction_using_ML.ipynb ./Air_Quality_Prediction_using_ML.ipynb

In [7]:
!find /content/drive -name "Air_Quality_Prediction_using_ML.ipynb"

/content/drive/MyDrive/Colab Notebooks/Air_Quality_Prediction_using_ML.ipynb

In [ ]:
import shutil
shutil.copy("/content/drive/MyDrive/Colab Notebooks/Air_Quality_Prediction_using_ML.ipynb", "/content/AirQualityPrediction/")

'/content/AirQualityPrediction/Air_Quality_Prediction_using_ML.ipynb'

In [ ]:
%cd /content/AirQualityPrediction

/content/AirQualityPrediction

In [10]:
!git add Air_Quality_Prediction_using_ML.ipynb
!git commit -m "Added Colab notebook"

[main fd22fad] Added Colab notebook
 1 file changed, 4000 insertions(+)
 create mode 100644 Air_Quality_Prediction_using_ML.ipynb

In [15]:
!git push https://AirQualityPrediction_Token@github.com/Jeevanandhini-18/AirQualityPrediction.git main

fatal: could not read Password for 'https://AirQualityPrediction_Token@github.com': No such device or address

In [16]:
!git push https://github.com/Jeevanandhini-18/AirQualityPrediction.git main

fatal: could not read Username for 'https://github.com': No such device or address

In [17]:
# Remove the current origin if it's misconfigured
!git remote remove origin

# Add remote using HTTPS
!git remote add origin https://github.com/Jeevanandhini-18/AirQualityPrediction.git

# Set the branch name explicitly to 'main'
!git branch -M main

In [18]:
!git push https://Shwetha-29:Colab_Github_Token@github.com/Jeevanandhini-18/AirQualityPrediction.git main

remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/Jeevanandhini-18/AirQualityPrediction.git/'